---
apiVersion: v1
kind:       Service
metadata:
  namespace: {{ .Values.docker_ui_namespace }}
  name:      {{ .Release.Name }}
  labels:
    app: {{ template "k8s-docker-ui.name" . }}
    chart: {{ template "k8s-docker-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  selector:
    app: {{ template "k8s-docker-ui.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name:       http
    protocol:   TCP
    port:       80
    targetPort: 80
