---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docker-ui
  namespace: do
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:1.4.*
spec:
  releaseName: docker-ui
  helmVersion: v3
  chart:
    git: git@github.com:Staudenmaier/k8s
    ref: master
    path: k8s-docker-ui/charts
    version: 0.0.3
    name: docker-ui
  values:
    image: joxit/docker-registry-ui:1.4.0
